version: '2'

services:
  backend:
    build: .
    pull_policy: build
    container_name: canny-github-bridge
    restart: unless-stopped
    ports:
      - '$PORT:$PORT'
    env_file:
      - stack.env